@echo off
setlocal EnableExtensions

REM Point test-ui at local Ollama.
REM Default model: qwen2.5:7b — strong open tool-calling / instruct model.

cd /d "%~dp0"
set "ENVFILE=%CD%\.env"
set "MODEL=qwen2.5:3b"

where ollama >nul 2>&1
if errorlevel 1 (
  echo Ollama not found on PATH.
  echo Install from https://ollama.com then re-run this script.
  pause
  exit /b 1
)

echo.
echo Pulling %MODEL% ^(one-time download^)...
ollama pull %MODEL%
if errorlevel 1 (
  echo Pull failed. Try a smaller model: ollama pull qwen2.5:3b
  pause
  exit /b 1
)

(
  echo # Generated by setup-ollama.bat
  echo LLM_BASE_URL=http://127.0.0.1:11434/v1
  echo LLM_MODEL=%MODEL%
  echo LLM_API_KEY=
  echo LLM_MODE=live
  echo.
  echo RAG_BACKEND=local
  echo HOST=0.0.0.0
  echo PORT=8787
) > "%ENVFILE%"

echo.
echo Wrote test-ui\.env  model=%MODEL%  mode=live
echo Next: start.bat
echo.
echo Fits 4GB GPU: qwen2.5:3b ^(default^)
echo More VRAM:    ollama pull qwen2.5:7b  then set LLM_MODEL=qwen2.5:7b in .env
echo.
echo IMPORTANT: Close AnythingLLM Desktop built-in Ollama if chat stays on CPU.
echo   It steals port 11434 with an old CPU engine. Use system Ollama instead.
echo.
pause
