@echo off
setlocal EnableExtensions

REM Writes OpenAI settings into test-ui\.env (gitignored).
REM Does not print the key.

cd /d "%~dp0"
set "ENVFILE=%CD%\.env"
set "EXAMPLE=%CD%\.env.example"

if not exist "%ENVFILE%" copy "%EXAMPLE%" "%ENVFILE%" >nul

echo.
echo === OpenAI setup for test-ui ===
echo Get a key: https://platform.openai.com/api-keys
echo ^(ChatGPT Plus alone is not enough — you need an API key.^)
echo.

set "KEY="
set /p KEY=Paste OpenAI API key then Enter: 
if "%KEY%"=="" (
  echo No key entered.
  pause
  exit /b 1
)

REM Rewrite .env with OpenAI live settings (keep other lines if we can — simple replace file)
(
  echo # Generated by setup-openai.bat
  echo LLM_BASE_URL=https://api.openai.com/v1
  echo LLM_MODEL=gpt-4o-mini
  echo LLM_API_KEY=%KEY%
  echo LLM_MODE=live
  echo.
  echo RAG_BACKEND=local
  echo HOST=0.0.0.0
  echo PORT=8787
) > "%ENVFILE%"

echo.
echo Saved to test-ui\.env  ^(LLM_MODE=live, model=gpt-4o-mini^)
echo Key was not displayed. Run start.bat next.
echo.
pause
